version: "3"
services:
  backend:
    build: ./backend
    container_name: backend_vphrase
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgres://user:password@db:5432/movies

  frontend:
    build: ./frontend/vphrase
    container_name: frontent_vphrase
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

#   db:
#     image: postgres:14
#     environment:
#       - POSTGRES_DB=movies
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
